### ISSUE TITLE
Build is passing but can't start server

### ISSUE THREAD

**Issue by rweigel** [hapi-server/server-nodejs#13]
The following commands lead to the error that follows. The issue has been fixed, but this type of error should have caused the build to fail. Please investigate.

```
git clone https://github.com/hapi-server/server-nodejs
cd server-nodejs
npm install
node server.js --port 8998 --ignore -f metadata/TestData2.0.json
```

```
TypeError: ds is not a function
    at checkcat (/home/ubuntu/server-nodejs-dev/lib/metadata.js:337:17)
    at checkinfo (/home/ubuntu/server-nodejs-dev/lib/metadata.js:366:5)
    at createcat (/home/ubuntu/server-nodejs-dev/lib/metadata.js:332:4)
    at updatemetadata (/home/ubuntu/server-nodejs-dev/lib/metadata.js:308:3)
    at prepmetadata (/home/ubuntu/server-nodejs-dev/lib/metadata.js:598:2)
    at Object.<anonymous> (/home/ubuntu/server-nodejs-dev/server.js:128:1)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
```

**Comment by KSR4599** [comment]
Sure. I will have a look at it.

**Comment by rweigel** [comment]
Probably build failed, not email sent by travis, then branch build succeeded. Have set travis to not build branches or forks. Still
